android_library(
  name = 'ExampleApp',
  srcs = glob(['*.java']),
  deps = [
    '//res/com/example/openspatial:res',
    '//release:OpenSpatialSDK',
    '//src/com/nod_labs/pointer:NodPointer',
    '//thirdparty:roboguice',
    '//thirdparty:guice',
    '//thirdparty:jsr330',
    '//thirdparty:jsr305',
  ],
  visibility = [
    '//apps/OpenSpatialExample:',
  ],
)

project_config(
  src_target = ':ExampleApp',
)

