android_resource(
  name = 'res',
  res = 'res',
  package = 'com.example.glassexample',
  visibility = [
    '//java/com/example/glassexample:',
    '//apps/GlassExample:',
  ]
)

project_config(
  src_target=':res',
  src_roots = None,
)
