android_library(
  name = 'glassexample',
  srcs = glob(['*.java']),
  deps = [
    '//libs:OpenSpatial',
    '//libs:NodPointer',
    '//libs:gdk',
    '//res/com/example/glassexample:res',
    '//libs:roboguice',
    '//libs:guice',
    '//libs:jsr330',
    '//libs:jsr305',
  ],
  visibility = [
    '//apps/GlassExample:'
  ]
)

project_config(
  src_target = ':glassexample',
)
