keystore(
  name = 'glassexample-app-keystore',
  store = 'GlassExample.keystore',
  properties = 'GlassExample.keystore.properties',
)

android_binary(
  name = 'GlassExample',
  manifest = 'AndroidManifest.xml',
  keystore = ':glassexample-app-keystore',
  deps = [
    '//res/com/example/glassexample:res',
    '//java/com/example/glassexample:glassexample'
  ],
)

project_config(
  src_target=':GlassExample',
)
