android_library(
  name = 'UnityOpenSpatialPlugin',
  srcs = glob(['*.java']),
  deps = [
    '//release:OpenSpatialSDK',
    '//thirdparty:unity'
  ],
  visibility = [
    'PUBLIC',
  ],
)

project_config(
  src_target = ':UnityOpenSpatialPlugin',
)
